trigger:
- main

pool:
  name: Default
  demands:
  - agent.name -equals prodvm

steps:
- script: |
    cd /var/www/deewan/deewan-spark-flow
    sudo systemctl stop deewan-spark-flow.service
    sudo kill -9 $(sudo lsof -t -i:3000) || true
    git pull origin main  # or however you sync files
    npm install
    npm install --save-dev @vitejs/plugin-react-swc
    npm install -D terser
    npm run optimize-images
    npm run build
    sudo systemctl start deewan-spark-flow.service
    nohup npm run preview:server > preview.log 2>&1 &
  displayName: Build and restart app locally
